version: "1.2"

services:
  product-service:
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    image: product-service
    container_name: product-service
    ports:
      - "3001:3001"
    networks:
      - my_network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: ./Dockerfile
    image: payment-service
    container_name: payment-service
    ports:
      - "3002:3002"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
